### PR TITLE
Setting up python packaging

### PR DESCRIPTION
**Pull request by Zeitsperre**
@huard I'm working on turning this into a package as a pilot project to understand how packaging works. I'm following many of the conventions presented [here](https://packaging.python.org/tutorials/packaging-projects/). Have any tips/suggestions?

### CODE REVIEW

**Comment by huard** [comment]
Nope, except to draw inspiration from the other pavics repos for consistency. You can assume that was Carsten is doing is worth copying.

**Comment by Zeitsperre** [comment]
@huard I came across a library ([CookieCutter](https://github.com/audreyr/cookiecutter)) which might help for converting these packages in the future. Based on several example layouts, it performs most of the packaging structure according to modern conventions. I might still try using it for Ouranosinc/pymerra2.

A relevant PyCon talk I came across: ["Share Your Code: Python Packaging Without Complication"](https://www.youtube.com/watch?v=qOH-h-EKKac)

**Comment by huard** [comment]
Yep, I used that to create a cookie-cutter template for the birdhouse birds with Carsten.
https://github.com/bird-house/cookiecutter-birdhouse

**Comment by Zeitsperre** [comment]
"A man ceases to be a beginner in any given science and becomes a master in that science when he has learned that he is going to be a beginner all his life." - R.G. Collingwood

**Pull request merged**
